name: sepolia

on:
  push:
  schedule:
    - cron: '0 */2 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        tag: ['https://twitter.com/chipittos1/status/1582025356202348544']
    steps:
    - uses: actions/checkout@v2
    - name: Cache requirements
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
    - name: Test with behave
      run: |
        python3 sepolia_ui.py ${{ matrix.tag }}
